# Generated by Django 5.0.6 on 2024-05-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('client_number', models.PositiveIntegerField(max_length=6)),
                ('phone_number', models.PositiveIntegerField(max_length=10)),
                ('date_joined', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
